services:
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - '15672:15672'
  server-main:
    build:
      context: ./server-main
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .server-main.env
      - .globals.env
  server-mailer:
    build:
      context: ./server-mailer
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - .server-mailer.env
      - .globals.env
    volumes:
      - ./email-templates:/email-templates:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

