services:
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - '15672:15672'
  server-main:
    build:
      context: ./server-main
    ports:
      - "8000:8000"
    env_file:
      - .server-main.env
  server-mailer:
    build:
      context: ./server-mailer
    depends_on:
      - rabbitmq
    env_file:
      - .server-mailer.env
    volumes:
      - ./email-templates:/email-templates:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

