version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:alpine
  server-main:
    build:
      context: ./server-main
    ports:
      - "8000:8000"
    env_file:
      - .server-main.env
  server-mailer:
    build:
      context: ./server-mailer
    depends_on:
      - rabbitmq
    env_file:
      - server-mailer.env
