version: '3.8'

services:
  server_main:
    build:
      context: ./server-main
    ports:
      - "8000:8000"
    networks:
      - monorepo-network
    env_file:
      - .server_main.env
      - .email.env
networks:
  monorepo-network:
