""" ""

Revision ID: 19874348a789
Revises: 211ee08c322b
Create Date: 2024-07-25 19:42:54.634126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "19874348a789"
down_revision: Union[str, None] = "211ee08c322b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=256), nullable=True)
    )
    op.add_column("users", sa.Column("verified", sa.Boolean(), nullable=True))
    op.drop_column("users", "at")
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "verified")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
