version: '3.8'

services:
  migrate:
    build: .
    command: ["poetry", "run", "alembic", "upgrade", "head"]
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      ISDOCKER: 1
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:

